language: node_js
node_js:
  - "6"

# Handle git submodules yourself
git:
    submodules: false

before_install:
# node 
    - npm install -g eslint

# cocos setup 
    - git clone http://github.com/cocos2d/cocos2d-x.git
    - cd ./cocos2d-x
    - python download-deps.py -r yes
    - git submodule update --init
    - mkdir ~/.cocos
    - cp ../local_cfg.json ~/.cocos/local_cfg.json
    - cat ~/.cocos/local_cfg.json
    - cd ./tools/cocos2d-console/
    - python download-bin.py -r yes
    - cd ../../
    - export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
    - export PATH=$PATH:$COCOS_CONSOLE_ROOT
    - export COCOS_TEMPLATES_ROOT=`pwd`/templates
    - export PATH=$PATH:$COCOS_TEMPLATES_ROOT
    - export ANT_ROOT=/usr/share/ant/bin
    - export PATH=$PATH:$ANT_ROOT
    - cd ..
    - echo `pwd`
    - printenv
    - cocos -v
    - cd cocos2d

script:
    - eslint 'src/*.js'
    - cocos compile -p web -m release
